### ISSUE TITLE
Concurrent issue in MemberOfCheck

### ISSUE THREAD

**Issue by pengbo** [sebthom/oval#102]
The following issue occurs in our environment:

```
java.lang.ArrayIndexOutOfBoundsException: 3
at java.util.ArrayList.indexOf(ArrayList.java:321)
at java.util.ArrayList.contains(ArrayList.java:304)
at net.sf.oval.constraint.MemberOfCheck.isSatisfied(MemberOfCheck.java:109)
at net.sf.oval.Validator._checkConstraint(Validator.java:568)
at net.sf.oval.Validator.checkConstraint(Validator.java:864)
at net.sf.oval.Validator._validateObjectInvariants(Validator.java:604)
at net.sf.oval.Validator._validateObjectInvariants(Validator.java:632)
at net.sf.oval.Validator.validateInvariants(Validator.java:1447)
at net.sf.oval.Validator.validate(Validator.java:1352)
......
at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:931)
at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:992)
at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:856)
at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:627)
at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:51)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
at java.lang.Thread.run(Thread.java:882)
```

After some investigations, we found that the variable **_membersLowerCase_** in **_MemberOfCheck_** is an **_ArrayList_** which may have concurrent  issue in lazy initializtion.

```
	private List<String> getMembersLowerCase()
	{
		if (membersLowerCase == null)
		{
			membersLowerCase = getCollectionFactory().createList(members.size());
			for (final String val : members)
				membersLowerCase.add(val.toLowerCase(Locale.getDefault()));
		}
		return membersLowerCase;
	}
```

Please have a look.

Thanks.

**Comment by sebthom** [comment]
Thanks for reporting. Will be fixed in 3.1.2, which builds right now.
