### ISSUE TITLE
matchPattern xml schema not match the xstream converter

### ISSUE THREAD

**Issue by cjdxhjj** [sebthom/oval#33]
according to your xml schema, i got an error. here is my code fragment

```xml
<matchPattern matchAll="true" errorCode="20018" message="手机号格式错误">
      <pattern pattern="^1[3-9]\d{9}$"/>
 </matchPattern>
````

and the error is
```
---- Debugging information ----
cause-exception     : java.lang.RuntimeException
cause-message       : null
class               : java.util.regex.Pattern
required-type       : java.util.regex.Pattern
converter-type      : com.thoughtworks.xstream.converters.extended.RegexPatternConverter
path                : /oval/class/field[7]/matchPattern/pattern
line number         : 26
class[1]            : net.sf.oval.constraint.MatchPatternCheck
required-type[1]    : net.sf.oval.constraint.MatchPatternCheck
converter-type[1]   : cn.dbn.userCenter.xml.XmlConfigurerFactory$configureXStream$1
class[2]            : net.sf.oval.configuration.pojo.elements.FieldConfiguration
required-type[2]    : net.sf.oval.configuration.pojo.elements.FieldConfiguration
class[3]            : net.sf.oval.configuration.pojo.elements.ClassConfiguration
required-type[3]    : net.sf.oval.configuration.pojo.elements.ClassConfiguration
class[4]            : net.sf.oval.configuration.pojo.POJOConfigurer
required-type[4]    : net.sf.oval.configuration.pojo.POJOConfigurer
version             : 1.4.11.1
-------------------------------
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:510)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:240)
	at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:721)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:534)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:743)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:390)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1214)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1203)
	at cn.dbn.userCenter.web.AppMainKt.main(AppMain.kt:17)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
```

my xstream is up to date and oval is 2.0.0
then i debug into the xstream parser, i found

```java
public class RegexPatternConverter implements Converter {

    /**
     * @since 1.4.5
     */
    public RegexPatternConverter() {
    }

    /**
     * @deprecated As of 1.4.5, use {@link #RegexPatternConverter()} instead
     */
    public RegexPatternConverter(Converter defaultConverter) {
    }

    public boolean canConvert(final Class type) {
        return type == Pattern.class;
    }

    public void marshal(Object source, HierarchicalStreamWriter writer, MarshallingContext context) {
        Pattern pattern = (Pattern)source;
        writer.startNode("pattern");
        writer.setValue(pattern.pattern());
        writer.endNode();
        writer.startNode("flags");
        writer.setValue(String.valueOf(pattern.flags()));
        writer.endNode();
    }

    public Object unmarshal(HierarchicalStreamReader reader, UnmarshallingContext context) {
        reader.moveDown();
        String pattern = reader.getValue();
        reader.moveUp();
        reader.moveDown();
        int flags = Integer.parseInt(reader.getValue());
        reader.moveUp();
        return Pattern.compile(pattern, flags);
    }

}
```

that show pattern and flags and node element，and flags is not optional, but the schema is 
```xml
<complexType name="MatchPattern" mixed="true">
        <annotation>
            <documentation>
                Check if the specified regular expression pattern is matched.
                Note: This constraint is also satisfied
                when the value to validate is
                null, therefore you might also need to declare the
                NotNull constraint.
            </documentation>
        </annotation>
        <complexContent>
            <extension base="tns:Constraint">
                <sequence>
                    <element name="pattern" minOccurs="0" maxOccurs="unbounded">
                        <complexType>
                            <attribute name="flags" type="integer" use="optional" />
                            <attribute name="pattern" type="string" use="required" />
                        </complexType>
                    </element>
                </sequence>
                <attribute name="matchAll" type="boolean" use="required" />
            </extension>
        </complexContent>
    </complexType>
```
this config need pattern and flags be a attributes on pattern element.
for the origin xstream demand, the config is complex, i provided an converter

```kotlin
class RegexPatternConverter : Converter {
    override fun canConvert(type: Class<*>): Boolean = type == Pattern::class.java

    override fun marshal(source: Any, writer: HierarchicalStreamWriter, context: MarshallingContext) {
        val pattern = source as Pattern
        writer.startNode("pattern")
        writer.addAttribute("pattern", pattern.pattern())
        writer.addAttribute("flags", pattern.flags().toString())
        writer.endNode()
    }

    override fun unmarshal(reader: HierarchicalStreamReader, context: UnmarshallingContext): Any {
        val pattern = reader.getAttribute("pattern")
        val flg = reader.getAttribute("flags")
        return if (flg != null) {
            val flags = Integer.parseInt(flg)
            Pattern.compile(pattern, flags)
        } else Pattern.compile(pattern)
    }
}
```

reg to xstream, it work great. here is my factory

```kotlin
class XmlConfigurerFactory(private val xStream: XStream, private val xmlConfigs: Array<Resource>, private val converters: Array<ConverterMatcher>) {
    private val listeners: Set<CheckInitializationListener> = LinkedHashSet(2)
    val configurers: Collection<Configurer>
        get() {
            configureXStream()
            val configurers = ArrayList<Configurer>(xmlConfigs.size)
            for (resource in xmlConfigs) {
                try {
                    configurers.add(XMLConfigurer(xStream, resource))
                } catch (e: IOException) {
                    e.printStackTrace()
                }
            }
            return configurers
        }

    private class ListConverter(mapper: Mapper) : CollectionConverter(mapper) {
        override fun canConvert(type: Class<*>): Boolean = List::class.java.isAssignableFrom(type)
    }

    private fun configureXStream() {
        xStream.registerConverter(object : ReflectionConverter(xStream.mapper, xStream.reflectionProvider) {
            override fun unmarshal(reader: HierarchicalStreamReader, context: UnmarshallingContext): Any {
                val instance = super.unmarshal(reader, context)
                if (instance is Check)
                    for (listener in listeners)
                        listener.onCheckInitialized(instance)
                return instance
            }
        }, XStream.PRIORITY_VERY_LOW)
        if (converters.isNotEmpty()) {
            for (i in converters.indices) {
                when {
                    converters[i] is Converter -> xStream.registerConverter(this.converters[i] as Converter, i)
                    this.converters[i] is SingleValueConverter -> xStream.registerConverter(this.converters[i] as SingleValueConverter, i)
                    else -> throw IllegalArgumentException("Invalid ConverterMatcher [" + this.converters[i] + "]")
                }
            }
        }
        xStream.registerConverter(ListConverter(xStream.mapper))
        //xStream.registerConverter(AssertCheckConverter())
        xStream.omitField(AbstractCheck::class.java, "messageVariablesUpToDate")
        xStream.useAttributeFor(Class::class.java)
        xStream.useAttributeFor(Boolean::class.javaPrimitiveType)
        xStream.useAttributeFor(Byte::class.javaPrimitiveType)
        xStream.useAttributeFor(Char::class.javaPrimitiveType)
        xStream.useAttributeFor(Double::class.javaPrimitiveType)
        xStream.useAttributeFor(Float::class.javaPrimitiveType)
        xStream.useAttributeFor(Int::class.javaPrimitiveType)
        xStream.useAttributeFor(Long::class.javaPrimitiveType)
        xStream.useAttributeFor(Boolean::class.java)
        xStream.useAttributeFor(Byte::class.java)
        xStream.useAttributeFor(Char::class.java)
        xStream.useAttributeFor(Double::class.java)
        xStream.useAttributeFor(Float::class.java)
        xStream.useAttributeFor(Int::class.java)
        xStream.useAttributeFor(Long::class.java)
        xStream.useAttributeFor(String::class.java)
        xStream.alias("java-type", Class::class.java)
        xStream.alias("constraintTarget", ConstraintTarget::class.java)
        // constraint check short forms
        xStream.alias("assert", AssertCheck::class.java)
        xStream.alias("assertConstraintSet", AssertConstraintSetCheck::class.java)
        xStream.alias("assertFalse", AssertFalseCheck::class.java)
        xStream.alias("assertFieldConstraints", AssertFieldConstraintsCheck::class.java)
        xStream.alias("assertNull", AssertNullCheck::class.java)
        xStream.alias("assertTrue", AssertTrueCheck::class.java)
        run {
            xStream.alias("assertURL", AssertURLCheck::class.java)
            xStream.alias("permittedURIScheme", AssertURLCheck.URIScheme::class.java)
            xStream.addImplicitCollection(AssertURLCheck::class.java, "permittedURISchemes", AssertURLCheck.URIScheme::class.java)
        }
        xStream.alias("assertValid", AssertValidCheck::class.java)
        xStream.alias("checkWith", CheckWithCheck::class.java)
        xStream.alias("dateRange", DateRangeCheck::class.java)
        xStream.alias("digits", DigitsCheck::class.java)
        xStream.alias("email", EmailCheck::class.java)
        xStream.alias("equalToField", EqualToFieldCheck::class.java)
        xStream.alias("future", FutureCheck::class.java)
        xStream.alias("hasSubstring", HasSubstringCheck::class.java)
        xStream.alias("instanceOf", InstanceOfCheck::class.java)
        xStream.alias("instanceOfAny", InstanceOfAnyCheck::class.java)
        xStream.alias("length", LengthCheck::class.java)
        run {
            xStream.alias("matchPattern", MatchPatternCheck::class.java)
            xStream.alias("pattern", Pattern::class.java)
            xStream.addImplicitCollection(MatchPatternCheck::class.java, "patterns", Pattern::class.java)
        }
        xStream.alias("max", MaxCheck::class.java)
        xStream.alias("maxLength", MaxLengthCheck::class.java)
        xStream.alias("maxSize", MaxSizeCheck::class.java)
        xStream.alias("memberOf", MemberOfCheck::class.java)
        xStream.alias("min", MinCheck::class.java)
        xStream.alias("minLength", MinLengthCheck::class.java)
        xStream.alias("minSize", MinSizeCheck::class.java)
        xStream.alias("noSelfReference", NoSelfReferenceCheck::class.java)
        xStream.alias("notBlank", NotBlankCheck::class.java)
        xStream.alias("notEmpty", NotEmptyCheck::class.java)
        xStream.alias("notEqual", NotEqualCheck::class.java)
        xStream.alias("notEqualToField", NotEqualToFieldCheck::class.java)
        run {
            xStream.alias("notMatchPattern", NotMatchPatternCheck::class.java)
            xStream.addImplicitCollection(NotMatchPatternCheck::class.java, "patterns", Pattern::class.java)
        }
        xStream.alias("notMemberOf", NotMemberOfCheck::class.java)
        xStream.alias("notNegative", NotNegativeCheck::class.java)
        xStream.alias("notNull", NotNullCheck::class.java)
        xStream.alias("past", PastCheck::class.java)
        xStream.alias("range", RangeCheck::class.java)
        xStream.alias("simpleCheck", CheckWithCheck.SimpleCheck::class.java)
        xStream.alias("size", SizeCheck::class.java)
        xStream.alias("validateWithMethod", ValidateWithMethodCheck::class.java)
        // check exclusions short forms
        xStream.alias("nullable", NullableExclusion::class.java)
        // <oval> -> net.sf.oval.configuration.POJOConfigurer
        xStream.alias("oval", POJOConfigurer::class.java)
        run {
            // <constraintSet> -> net.sf.oval.configuration.elements.ConstraintSetConfiguration
            xStream.addImplicitCollection(POJOConfigurer::class.java, "constraintSetConfigurations", ConstraintSetConfiguration::class.java)
            xStream.alias("constraintSet", ConstraintSetConfiguration::class.java)
            xStream.addImplicitCollection(ConstraintSetConfiguration::class.java, "checks")

            // <class> -> net.sf.oval.configuration.elements.ClassConfiguration
            xStream.addImplicitCollection(POJOConfigurer::class.java, "classConfigurations", ClassConfiguration::class.java)
            xStream.alias("class", ClassConfiguration::class.java)
            run {
                // <object> -> net.sf.oval.configuration.elements.ObjectConfiguration
                xStream.aliasField("object", ClassConfiguration::class.java, "objectConfiguration")
                run { xStream.addImplicitCollection(ObjectConfiguration::class.java, "checks") }
                // <field> -> net.sf.oval.configuration.elements.FieldConfiguration
                xStream.addImplicitCollection(ClassConfiguration::class.java, "fieldConfigurations", FieldConfiguration::class.java)
                xStream.alias("field", FieldConfiguration::class.java)
                xStream.addImplicitCollection(FieldConfiguration::class.java, "checks")
                // <parameter> -> net.sf.oval.configuration.elements.ParameterConfiguration
                // used within ConstructorConfiguration and MethodConfiguration
                xStream.alias("parameter", ParameterConfiguration::class.java)
                xStream.addImplicitCollection(ParameterConfiguration::class.java, "checks", Check::class.java)
                xStream.addImplicitCollection(ParameterConfiguration::class.java, "checkExclusions", CheckExclusion::class.java)
                // <constructor> -> net.sf.oval.configuration.elements.ConstructorConfiguration
                xStream.addImplicitCollection(ClassConfiguration::class.java, "constructorConfigurations", ConstructorConfiguration::class.java)
                xStream.alias("constructor", ConstructorConfiguration::class.java)
                run {
                    // <parameter> -> net.sf.oval.configuration.elements.ParameterConfiguration
                    xStream.addImplicitCollection(ConstructorConfiguration::class.java, "parameterConfigurations", ParameterConfiguration::class.java)
                }
                // <method> -> net.sf.oval.configuration.elements.MethodConfiguration
                xStream.addImplicitCollection(ClassConfiguration::class.java, "methodConfigurations", MethodConfiguration::class.java)
                xStream.alias("method", MethodConfiguration::class.java)
                run {
                    // <parameter> -> net.sf.oval.configuration.elements.ParameterConfiguration
                    xStream.addImplicitCollection(MethodConfiguration::class.java, "parameterConfigurations", ParameterConfiguration::class.java)
                    // <returnValue> -> net.sf.oval.configuration.elements.MethodConfiguration.returnValueConfiguration
                    // -> MethodReturnValueConfiguration
                    xStream.aliasField("returnValue", MethodConfiguration::class.java, "returnValueConfiguration")
                    xStream.addImplicitCollection(MethodReturnValueConfiguration::class.java, "checks", Check::class.java)
                    // <pre> -> net.sf.oval.configuration.elements.MethodConfiguration.preExecutionConfiguration ->
                    // MethodPreExecutionConfiguration
                    xStream.aliasField("preExecution", MethodConfiguration::class.java, "preExecutionConfiguration")
                    xStream.addImplicitCollection(MethodPreExecutionConfiguration::class.java, "checks", PreCheck::class.java)
                    xStream.alias("pre", PreCheck::class.java)
                    // <post> -> net.sf.oval.configuration.elements.MethodConfiguration.postExecutionConfiguration ->
                    // MethodPostExecutionConfiguration
                    xStream.aliasField("postExecution", MethodConfiguration::class.java, "postExecutionConfiguration")
                    xStream.addImplicitCollection(MethodPostExecutionConfiguration::class.java, "checks", PostCheck::class.java)
                    xStream.alias("post", PostCheck::class.java)
                }
            }
        }
    }
}
```

this improvement my app startup, and make me config easier， can you provider inside oval?

**Comment by sebthom** [comment]
This was a nice catch, thanks! Now I can finally upgrade the XStream version! :-)

**Comment by sebthom** [comment]
Version 2.0.1 is now available, having both of your reported issues fixed.

**Comment by cjdxhjj** [comment]
thanks very much, work with oval is pleasant.

**Comment by bharattrikha03** [comment]
Was facing the same issue could you tell where have to posted the oval 2.0.1 jar ?

**Comment by cjdxhjj** [comment]
jcenter

**Comment by sebthom** [comment]
https://bintray.com/sebthom/maven/oval

**Comment by bharattrikha03** [comment]
thanks its working now :)
