### ISSUE TITLE
@Past and @Future not working for java.time.* API

### ISSUE THREAD

**Issue by Pyeroh** [sebthom/oval#5]
Annotations like @Past and @Future (and checking classes associated) don't work with Java 8 date representations, as they are not parsable (at least for my locale)

Yes, I know I can create my own checking class, but I would need to also create my own annotation, so to basically copy your annotations into my code, and modify it a bit to fit my needs.

It would be nice to have this feature in your framework. Maybe you'd prefer a pull request ?

**Comment by sebthom** [comment]
I wouldn't mind a pull request, however it should compile with JDK5 as this is still the target for OVal (yes I know Java 5/6 are EoL but I have customers still using it). 

For JSR223 for example the project references a JDK5 backport maybe something exists for JSR 310 too.

**Comment by sebthom** [comment]
Please give it a try: http://oval.sourceforge.net/mvn-repo/snapshot/net/sf/oval/oval/1.87-SNAPSHOT/

**Comment by Pyeroh** [comment]
I tried this snapshot, but it's failing with a java.lang.IncompatibleClassChangeError on the return instruction line. If I evaluate the expression in debug mode, nothing's wrong, but when I step forward, this error occurs. Maybe because it was not compiled with Java8 ?

**Comment by sebthom** [comment]
Can you give me the full stacktrace of the error?

**Comment by Pyeroh** [comment]
`java.lang.IncompatibleClassChangeError: Found class java.time.LocalDateTime, but interface was expected
	at net.sf.oval.constraint.PastCheck.isJavaTimeSatisfied(PastCheck.java:65)
	at net.sf.oval.constraint.PastCheck.isSatisfied(PastCheck.java:107)
	at net.sf.oval.Validator._checkConstraint(Validator.java:571)
	at net.sf.oval.Validator.checkConstraint(Validator.java:845)
	at net.sf.oval.Validator._validateObjectInvariants(Validator.java:602)
	at net.sf.oval.Validator.validateInvariants(Validator.java:1384)
	at net.sf.oval.Validator.validate(Validator.java:1308)
	at nc.escalade.easycompet.utils.validation.impl.ValidatorImpl.validate(ValidatorImpl.java:23)
	at nc.escalade.easycompet.TestingTest.test_test(TestingTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:377)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by sebthom** [comment]
Please try again with the new snapshot,

**Comment by Pyeroh** [comment]
Tested success and failure, on Future and Past, and it works perfectly. 

BTW, I looked at your commit, and it's a very clever way to avoid compiling against a JDK you're not using, I'll remember it the next time I face it !

Thanks for your *time* (pun intended), and for your work on this awesome lib !

**Comment by sebthom** [comment]
I uploaded v1.87 to https://oss.sonatype.org/index.html#nexus-search;quick~oval

Should appear in repo1 within 1 day.

**Comment by Pyeroh** [comment]
Thank you
